---

- name: Debian - Add Grafana repository key
  apt_key: url="https://packagecloud.io/gpg.key" state=present

- name: Add Grafana Repository
  apt_repository: repo="deb https://packagecloud.io/grafana/stable/debian/ stretch main" state=present

- name: Install Grafana
  apt:
   name: grafana
   update_cache: yes

- name: Start Grafana Service
  service: name=grafana-server enabled=yes state=restarted
