- name: update apt package cache
  apt: update_cache=yes

- name: install common packages debian/ubuntu
  apt: pkg={{ item }} state=latest
  with_items:
    - software-properties-common
    - build-essential
    - git
    - vim